version: "3.9"

services:
  ichgram:
    build:
      context: ./BE
      dockerfile: dockerfile
    container_name: ichgram
    ports:
      - "5001:5001"
      - "5005:5005"

  frontichgram:
    build:
      context: ./FE
      dockerfile: dockerfile
    container_name: frontichgram
    ports:
      - "5173:5173"
